amazon:
  access:
    key: ${aws-key:dummy}
    secret-key: ${aws-secret-key:dummy}
  region: ap-northeast-1
  end-point:
    url: localhost:8000
server:
  port: 8080

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION